# Properties for Dev environment

# Headers
auth_id: "j32io33ise4k2qq1"

# MYSQL credentials
mysql:
  host: "127.0.0.1"
  port: "3306"
  username: "root"
  password: "Chamrell2020"
  database: "chami"
  